version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  web:
    build:
      context: .
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - fastapi
